const screenNames = {
  AUTH_STACK: 'AUTH_STACK',
  MAIN_STACK: 'MAIN_STACK',
  LANDING_SCREEN: 'LANDING_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTRATION_SCREEN: 'REGISTRATION_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
};

export default screenNames;
