const screenNames = {
  AUTH_STACK: 'AUTH_STACK',
  MAIN_STACK: 'MAIN_STACK',
  LANDING_SCREEN: 'LANDING_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTRATION_SCREEN: 'REGISTRATION_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  LOADING_SCREEN: 'LOADING_SCREEN',
  MAIN_BOTTOM_SCREEN: 'MAIN_BOTTOM_SCREEN',
  FEED_SCREEN: 'FEED_SCREEN',
  FEED_POST_STACK: 'FEED_POST_STACK',
  ADD_POST_SCREEN: 'ADD_POST_SCREEN',
  ARTWORK_LIST_SCREEN: 'ARTWORK_LIST_SCREEN',
  ARTWORK_DETAIL_SCREEN: 'ARTWORK_DETAIL_SCREEN',
  ARTWORK_API_STACK: 'ARTWORK_API_STACK',
  PROFILE_STACK: 'PROFILE_STACK',
  EDIT_PROFILE_SCREEN: 'EDIT_PROFILE_SCREEN',
  OTHER_PROFILE_SCREEN: 'OTHER_PROFILE_SCREEN',
};

export default screenNames;
