const screenNames = {
  AUTH_STACK: 'AUTH_STACK',
  MAIN_STACK: 'MAIN_STACK',
  LANDING_SCREEN: 'LANDING_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTRATION_SCREEN: 'REGISTRATION_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  LOADING_SCREEN: 'LOADING_SCREEN',
  MAIN_BOTTOM_SCREEN: 'MAIN_BOTTOM_SCREEN',
  FEED_SCREEN: 'FEED_SCREEN',
  FEED_POST_STACK: 'FEED_POST_STACK',
  ADD_POST_SCREEN: 'ADD_POST_SCREEN',
};

export default screenNames;
